<?php
/**
 * @package OpenXdmod
 * @subpackage Tests
 */

namespace Controllers;

use TestHarness\RegressionTestHelper;

/**
 * Test the usage explorer for storage realm regressions.
 */
class UsageExplorerStorageTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var \RegressionTestHelper
     */
    private static $helper;

    /**
     * Create the helper and authenticate.
     */
    public static function setUpBeforeClass()
    {
        self::$helper = new RegressionTestHelper();
        self::$helper->authenticate();
    }

    /**
     * Log out and output any messages generated by tests.
     */
    public static function tearDownAfterClass()
    {
        self::$helper->logout();
        self::$helper->outputMessages();
    }

    /**
     * Test usage explorer CSV export.
     *
     * @group regression
     * @group UsageExplorer
     * @dataProvider csvExportProvider
     */
    public function testCsvExport($testName, $input, $expectedFile, $userRole)
    {
        $this->assertTrue(self::$helper->checkCsvExport($testName, $input, $expectedFile, $userRole));
    }

    public function csvExportProvider()
    {
        $statistics = [
            'avg_file_count',
            'avg_logical_usage',
            'avg_physical_usage',
            'avg_logical_utilization',
            'avg_hard_threshold',
            'avg_soft_threshold',
            'user_count'
        ];

        $groupBys = [
            'none',
            'nsfdirectorate',
            'parentscience',
            'fieldofscience',
            'mountpoint',
            'pi',
            'resource',
            'resource_type',
            'username',
            'person'
        ];

        $settings = [
            'realm' => ['Storage'],
            'dataset_type' => ['aggregate', 'timeseries'],
            'statistic' => $statistics,
            'group_by' => $groupBys,
            'aggregation_unit' => ['Day', 'Month', 'Quarter', 'Year']
        ];

        return RegressionTestHelper::generateTests($settings, '2018-12-27', '2019-01-05');
    }
}
