<?php
/**
 * @package OpenXdmod
 * @subpackage Tests
 */

namespace Controllers;

use TestHarness\RegressionTestHelper;

/**
 * Test the usage explorer for jobs realm regressions.
 */
class UsageExplorerJobsTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var \RegressionTestHelper
     */
    private static $helper;

    /**
     * Create the helper and authenticate.
     */
    public static function setUpBeforeClass()
    {
        self::$helper = new RegressionTestHelper();
        self::$helper->authenticate();
    }

    /**
     * Log out and output any messages generated by tests.
     */
    public static function tearDownAfterClass()
    {
        self::$helper->logout();
        self::$helper->outputMessages();
    }

    /**
     * Test usage explorer CSV export.
     *
     * @group regression
     * @group UsageExplorer
     * @dataProvider csvExportProvider
     */
    public function testCsvExport($testName, $input, $expectedFile, $userRole)
    {
        $this->assertTrue(self::$helper->checkCsvExport($testName, $input, $expectedFile, $userRole));
    }

    public function csvExportProvider()
    {
        /**
         * statistic names must be prefixed with  `${REALM_NAME}_`
         */
        $statistics = [
            'Jobs_active_person_count',
            'Jobs_active_pi_count',
            'Jobs_active_resource_count',
            'Jobs_avg_cpu_hours',
            'Jobs_avg_job_size_weighted_by_cpu_hours',
            'Jobs_avg_node_hours',
            'Jobs_avg_processors',
            'Jobs_avg_waitduration_hours',
            'Jobs_avg_wallduration_hours',
            'Jobs_expansion_factor',
            'Jobs_job_count',
            'Jobs_max_processors',
            'Jobs_min_processors',
            'Jobs_normalized_avg_processors',
            'Jobs_running_job_count',
            'Jobs_started_job_count',
            'Jobs_submitted_job_count',
            'Jobs_total_cpu_hours',
            'Jobs_total_node_hours',
            'Jobs_total_waitduration_hours',
            'Jobs_total_wallduration_hours',
            'Jobs_utilization'
        ];

        $groupBys = [
            'fieldofscience',
            'jobsize',
            'jobwalltime',
            'jobwaittime',
            'nodecount',
            'none',
            'nsfdirectorate',
            'parentscience',
            'person',
            'pi',
/**
 * Temporary comment to get tests to pass while known error is fixed
 * specifically allowing group bys to have additional where clauses
 */
//            'queue',
            'resource',
            'resource_type',
            'username'
        ];

        $settings = [
            'realm' => ['Jobs'],
            'dataset_type' => ['aggregate', 'timeseries'],
            'statistic' => $statistics,
            'group_by' => $groupBys,
            'aggregation_unit' => ['Day', 'Month', 'Quarter', 'Year']
        ];

        return RegressionTestHelper::generateTests($settings);
    }
}
