# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    annotations:
        enabled: false
    error_controller: CCR\Errors\ErrorController
    handle_all_throwables: true
    secret: '%env(APP_SECRET)%'
    csrf_protection: true
    http_method_override: false
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: strict
        storage_factory_id: session.storage.factory.native
    php_errors:
        log: true
when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
