security:
    password_hashers:
        CCR\Entity\User: 'auto'
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        username_provider:
            id: CCR\Security\UsernameUserProvider
        all_users:
            chain:
                providers: [ 'username_provider' ]
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        rest:
            pattern: ^/rest
            stateless: true
            access_token:
                token_handler: CCR\Security\TokenHandlers\JSONWebTokenHandler
                token_extractors: header
                provider: username_provider
        main:
            lazy: true
            provider: username_provider
            custom_authenticators:
                - CCR\Security\Authenticators\FormLoginAuthenticator
                - CCR\Security\Authenticators\SimpleSamlPhpAuthenticator
            switch_user: true
            logout:
              path: /logout
              target: xdmod_home
              enable_csrf: true
            access_denied_handler: CCR\Security\AccessDeniedHandler
            entry_point: CCR\Security\Authenticators\FormLoginAuthenticator

    access_control:
        - { path: ^/, roles: PUBLIC_ACCESS}
