ALTER TABLE modw_aggregates.jobfact_by_day 
  DROP INDEX index_last_modified,
  DROP INDEX index_period_value,
  DROP INDEX index_period,
  DROP INDEX index_account,
  DROP INDEX index_allocation,
  DROP INDEX index_fos,
  DROP INDEX index_job_time_bucket_id,
  DROP INDEX index_job_wait_time_bucket_id,
  DROP INDEX index_node_count,
  DROP INDEX index_person,
  DROP INDEX index_person_nsf_status_code,
  DROP INDEX index_person_organization,
  DROP INDEX index_pi_organization,
  DROP INDEX index_pi_person,
  DROP INDEX index_processor_count,
  DROP INDEX index_queue,
  DROP INDEX index_resource,
  DROP INDEX index_resource_organization,
  DROP INDEX index_resource_type,
  DROP INDEX index_system_account;

ALTER TABLE modw_aggregates.jobfact_by_day 
  ADD INDEX index_account (day_id,account_id),
  ADD INDEX index_allocation (day_id,allocation_id),
  ADD INDEX index_fos (day_id,fos_id),
  ADD INDEX index_job_time_bucket_id (day_id,job_time_bucket_id),
  ADD INDEX index_job_wait_time_bucket_id (day_id,job_wait_time_bucket_id),
  ADD INDEX index_last_modified (last_modified),
  ADD INDEX index_node_count (day_id,node_count),
  ADD INDEX index_period (day_id),
  ADD INDEX index_period_value (day),
  ADD INDEX index_person (day_id,person_id),
  ADD INDEX index_person_nsf_status_code (day_id,person_nsfstatuscode_id),
  ADD INDEX index_person_organization (day_id,person_organization_id),
  ADD INDEX index_pi_organization (day_id,piperson_organization_id),
  ADD INDEX index_pi_person (day_id,principalinvestigator_person_id),
  ADD INDEX index_processor_count (day_id,processor_count),
  ADD INDEX index_queue (day_id,queue),
  ADD INDEX index_resource (day_id,record_resource_id),
  ADD INDEX index_resource_organization (day_id,resource_organization_id),
  ADD INDEX index_resource_type (day_id,resourcetype_id),
  ADD INDEX index_system_account (day_id,systemaccount_id);