language: none
env:
    global:
        - COMPOSER_ALLOW_SUPERUSER=1
    matrix:
        - XDMOD_TEST_MODE=fresh_install
        - XDMOD_TEST_MODE=upgrade
build:
    cache: true
    cache_dir_list:
        - /root/.composer
        - /root/.npm
    pre_ci:
        - docker build -t pseudo_repo/openxdmod:latest .
    pre_ci_boot:
        image_name: pseudo_repo/openxdmod
        image_tag: latest
        pull: false
        options: "--user root -e HOME=/root --shm-size 2g"
    ci:
        - composer install --no-progress
        - ~/bin/buildrpm xdmod
        - ./tests/ci/bootstrap.sh
        - ./tests/ci/validate.sh
        - composer install --no-progress
        - ./tests/regression/runtests.sh --junit-output-dir `pwd`/shippable/testresults/
        - mv ./configuration/organization.json ./configuration/organization.json.old
        - mv ./configuration/portal_settings.ini ./configuration/portal_settings.ini.old
        - cp /etc/xdmod/portal_settings.ini ./configuration/portal_settings.ini
        - cp /etc/xdmod/organization.json ./configuration/organization.json
        - ./tests/integration/runtests.sh --junit-output-dir `pwd`/shippable/testresults/
        - ./tests/regression/post_ingest_test.sh --junit-output-dir `pwd`/shippable/testresults/
        - ./tests/component/runtests.sh --log-junit `pwd`/shippable/testresults/xdmod-component.xml
        - ./tests/ui/runtests.sh --headless --log-junit `pwd`/shippable/testresults
        - ./tests/ci/samlSetup.sh
        - ./tests/ui/runtests.sh --headless --log-junit `pwd`/shippable/testresults --sso
        - ./vendor/phpunit/phpunit/phpunit -c ./tests/integration/phpunit.xml.dist --testsuite sso --log-junit `pwd`/shippable/testresults/xdmod-sso-integration.xml
        - mv ./configuration/portal_settings.ini.old ./configuration/portal_settings.ini
        - test ! -s /var/log/xdmod/apache-error.log
    on_failure:
        - cat /var/log/xdmod/apache-error.log
        - cat /var/log/xdmod/exceptions.log
        - cat /var/log/xdmod/query.log
        - cat /var/log/xdmod/apache-access.log
jobs:
    - name: xdmod_runCI
      type: runCI
      steps:
        - IN: xdmod-time-trigger
      on_change:
        - NOTIFY: slack_notif
      on_failure:
        - NOTIFY: slack_notif
