language: none
env:
    - XDMOD_TEST_MODE=fresh_install
    - XDMOD_TEST_MODE=upgrade
build:
    cache: true
    cache_dir_list:
        - /root/.composer
        - /root/.npm
    pre_ci:
        - docker build -t pseudo_repo/openxdmod:latest .
    pre_ci_boot:
        image_name: pseudo_repo/openxdmod
        image_tag: latest
        pull: false
        options: "--user root -e HOME=/root --shm-size 2g"
    ci:
        - composer install --no-progress
        - ~/bin/buildrpm xdmod
        - ./tests/ci/bootstrap.sh
        - ./tests/ci/validate.sh
        - composer install --no-progress
        - ./tests/regression/runtests.sh --junit-output-dir `pwd`/shippable/testresults/
        - mv ./configuration/portal_settings.ini ./configuration/portal_settings.ini.old
        - cp /etc/xdmod/portal_settings.ini ./configuration/portal_settings.ini
        - ./tests/integration/runtests.sh --junit-output-dir `pwd`/shippable/testresults/
        - ./tests/regression/post_ingest_test.sh --junit-output-dir `pwd`/shippable/testresults/
        - ./tests/component/runtests.sh --log-junit `pwd`/shippable/testresults/xdmod-component.xml
        - ./tests/ui/runtests.sh --headless --log-junit `pwd`/shippable/testresults
        - ./tests/ci/samlSetup.sh
        - ./tests/ui/runtests.sh --headless --log-junit `pwd`/shippable/testresults --sso
        - ./vendor/phpunit/phpunit/phpunit -c ./tests/integration/phpunit.xml.dist --testsuite sso --log-junit `pwd`/shippable/testresults/xdmod-sso-integration.xml
        - mv ./configuration/portal_settings.ini.old ./configuration/portal_settings.ini
        - if [ -s /var/log/xdmod/apache-error.log ]; then cat /var/log/xdmod/apache-error.log; false; fi
    on_failure:
        - cat /var/log/xdmod/apache-error.log
        - cat /var/log/xdmod/exceptions.log
        - cat /var/log/xdmod/query.log
        - cat /var/log/xdmod/apache-access.log
integrations:
  notifications:
    - integrationName: slack-notification-xdmod
      type: slack
      recipients: "#shippable"
      on_success: change
      on_failure: always
      on_cancel: never
      on_start: never
      on_pull_request: never
resources:
  - name: xdmod-time-trigger
    type: time
    versionTemplate:
      interval: "0 2 * * *" # UTC
  - name: slack_notif
    type: notification
    integration: slack-notification-xdmod
    versionTemplate:
      recipients:
        - "#shippable"
jobs:
    - name: xdmod_runCI
      type: runCI
      steps:
        - IN: xdmod-time-trigger
      on_change:
        - NOTIFY: slack_notif
      on_failure:
        - NOTIFY: slack_notif
