FROM centos:8.4.2105
ENV BRANCH=xdmod10.0
LABEL description="Base image containing XDMoD required software."

COPY assets/google-chrome.repo /etc/yum.repos.d

# We need to fix things since they binned Centos8
RUN sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-* && \
    sed -i 's|#baseurl=http://mirror.centos.org|baseurl=https://vault.centos.org|g' /etc/yum.repos.d/CentOS-*

# We need to install the epel before installing XDMoD's dependencies.
RUN yum makecache && yum -y install epel-release

# These are the software pre-requisites for an XDMoD Install ( minus PHP )
RUN yum -y install \
    httpd \
    sudo \
    wget \
    vim \
    git \
    rpm-build \
    expect \
    make \
    gcc \
    gcc-c++ \
    openssl \
    rsync \
    nodejs \
    python39 \
    cronie \
    logrotate \
    ghostscript \
    jq \
    gnu-free-sans-fonts \
    google-chrome-stable \
    httpd \
    postfix \
    mariadb-server \
    mariadb

# This step covers PHP and the plugins required by XDMoD
RUN yum -y install \
    php \
    php-common \
    php-opcache \
    php-cli \
    php-gd \
    php-curl \
    php-pear \
    php-zip \
    php-gmp \
    php-pdo \
    php-xml \
    php-mbstring \
    php-mysqlnd \
    php-pecl-apcu \
    php-pecl-json

# Make sure to clean the cache and installs.
RUN yum clean all && rm -rf /var/cache/yum

# Directory needed by php-fpm
RUN mkdir -p /run/php-fpm

# Setup Timezone
RUN sed -i 's/.*date.timezone[[:space:]]*=.*/date.timezone = UTC/' /etc/php.ini && \
    sed -i 's/.*memory_limit[[:space:]]*=.*/memory_limit = -1/' /etc/php.ini
RUN rm /etc/localtime && ln -s /usr/share/zoneinfo/UTC /etc/localtime

# Setup Postfix
RUN sed -ie 's/inet_interfaces = localhost/#inet_interfaces = localhost/' /etc/postfix/main.cf  && \
    sed -ie 's/smtp      inet  n       -       n       -       -       smtpd/#smtp      inet  n       -       n       -       -       smtpd/' /etc/postfix/master.cf && \
    sed -ie 's/smtp      unix  -       -       n       -       -       smtp/smtp      unix  -       -       n       -       -       local/' /etc/postfix/master.cf && \
    sed -ie 's/relay     unix  -       -       n       -       -       smtp/relay     unix  -       -       n       -       -       local/' /etc/postfix/master.cf && \
    echo '/.*/ root' >> /etc/postfix/virtual && \
    postmap /etc/postfix/virtual && \
    echo 'virtual_alias_maps = regexp:/etc/postfix/virtual' >> /etc/postfix/main.cf && \
    newaliases

# Install composer
RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" && \
    EXPECTED_SIGNATURE="$(wget -q -O - https://composer.github.io/installer.sig)" && \
    ACTUAL_SIGNATURE="$(php -r "echo hash_file('SHA384', 'composer-setup.php');")" && \
    if [ "$EXPECTED_SIGNATURE" != "$ACTUAL_SIGNATURE" ]; then echo 'ERROR: Invalid composer signature'; exit 1; fi && \
    php composer-setup.php --install-dir=/bin --filename=composer && \
    php -r "unlink('composer-setup.php');" \
