<?php

namespace IntegrationTests\Rest;

class ReportThumbnailsTest extends \PHPUnit_Framework_TestCase
{
    protected static $helpers = array();

    public static function setUpBeforeClass()
    {
        foreach (array('cd', 'cs') as $user) {
            self::$helpers[$user] = new \TestHarness\XdmodTestHelper();
            if ($user != 'pub') {
                self::$helpers[$user]->authenticate($user);
            }
        }
    }

    public static function tearDownAfterClass()
    {
        foreach (self::$helpers as $helper) {
            $helper->logout();
        }
    }

    public function testCdReport()
    {
        $response = self::$helpers['cd']->get('rest/v1/summary/rolereport', null);
        $this->assertEquals(8, sizeof($response[0]['data']['queue']));

        // delete report
        $data = array(
            'operation' => 'remove_report_by_id',
            'selected_report' => '3-autogenerated-cd',
        );
        $response = self::$helpers['cd']->post('controllers/report_builder.php', null, $data);
        $this->assertTrue($response[0]['success']);
    }

    public function testCsReport()
    {
        $response = self::$helpers['cs']->get('rest/v1/summary/rolereport', null);
        $this->assertEquals(4, sizeof($response[0]['data']['queue']));

        // delete report
        $data = array(
            'operation' => 'remove_report_by_id',
            'selected_report' => '4-autogenerated-cd',
        );
        $response = self::$helpers['cs']->post('controllers/report_builder.php', null, $data);
        $this->assertTrue($response[0]['success']);
    }
}
