<?php

namespace UnitTests\Helper;

use CCR\Helper\SymfonyCommandHelper;
use PHPUnit\Framework\TestCase;

/**
 * This class is meant to provide some super basic tests for the SymfonyCommandHandler. This helper class allows us to
 * execute Symfony commands from PHP land without exlicitly calling Symfony's `bin/console` file.
 */
class SymfonyCommandHelperTest extends TestCase
{

    /**
     * Main test for executing various Symfony commands and checking the generated output (stdout) against what's
     * expected.
     *
     * @param string $command         the command to be executed.
     * @param string[] $expectedOutput an array of strings that are expected in the output generated by the $command.
     *
     * @return void
     *
     * @throws \Exception if there is a problem executing the provided $command.
     *
     * @dataProvider provideCommands
     */
    public function testCommandOutput(string $command, array $expectedOutput)
    {
        $commandHelper = new SymfonyCommandHelper();

        $output = $commandHelper->executeCommand($command);

        foreach ($expectedOutput as $expected) {
            $this->assertStringContainsStringIgnoringCase(
                $expected,
                $output,
                sprintf("Expected to find '%s' in %s", $expected, $output)
            );
        }

    }

    /**
     * Provides the test cases for `testCommandOutput`.
     *
     * @return array[]
     */
    public function provideCommands(): array
    {
        return [
            ['cache:clear', ['was successfully cleared']],
            ['dotenv:dump', ['Successfully dumped .env files in .env.local.php']],
            ['router:match /warehouse/dimensions', ['ccr_warehouse_getdimensions', ' CCR\Controller\WarehouseController::getDimensions()']]
        ];
    }
}
