<?php

namespace UnitTests\DataWarehouse\Access;

use \DataWarehouse\Access\ReportGenerator;

class ReportGeneratorTest extends \PHPUnit\Framework\TestCase
{

    public function reportTmpProvider() {
        $data = [];
        $data[]  = ['1-1579636800-yk3aoO', true];
        $data[]  = ['monthly_compliance_report-NoUbqQ', true];
        $data[]  = ['1-autogenerated-cd-iYuxZL', true];
        $data[]  = ['1-autogenerated-usr-iYuxZL', true];
        $data[]  = ['1-1579636800-../etc/shadow', false];
        $data[]  = ['1-autogeerated-usr-iYuxZL', false];
        $data[]  = ['../../root/.ssh/id_rsa', false];

        return $data;
    }

    public function reportIdProvider() {
        $data = [];
        $data[]  = ['1-1579636800', true];
        $data[]  = ['1021-1479636800.234', true];
        $data[]  = ['1021-autogenerated-cd', true];
        $data[]  = ['1021-autogenerated-usr', true];
        $data[]  = ['58-autoindent-cs;1', false];
        $data[]  = ['cat /etc/passwd', false];

        return $data;
    }

    public function chartRefProvider() {
        $data = [];
        $data[] = ['1-1579636800;2', true];
        $data[] = ['1;161', true];
        $data[] = ['4-1552934615.1928;5', true];
        $data[] = ['52-autogenerated-cd;7', true];
        $data[] = ['58-autogenerated-usr;1', true];
        $data[] = ['58-autogenerated-cs;1', true];
        $data[] = ['58-autoindent-cs;1', false];
        $data[] = ['/var/log/messages;161', false];
        $data[] = ['; SELECT * FROM Users;161', false];

        return $data;
    }

    public function cacheVarProvider() {
        $data = [];
        $data[] = ['2019-12-01;2019-12-31;1-1579636800;2', true];
        $data[] = ['2019-12-01;2019-12-31;160-1579636800.234;2', true];
        $data[] = ['2019-12-01;2019-12-31;xd_report_volatile_1;153', true];
        $data[] = ['2010-01-22;2020-01-22;xd_report_volatile_1;161_d1579741925', true];
        $data[] = ['2-1-22;2020-01-22;xd_report_volatile_1;161_d1579741925', false];
        $data[] = ['2010-03-02;2020-03-02;1-autogenerated-cd;3', true];
        $data[] = ['2010-03-02;2020-03-02;1-autogenerated-/var/log/messages;3', false];
        $data[] = ['2019-12-01;2019-12-31;../etc/passwd;2', false];

        return $data;
    }

    /*
     * run a regular expression via the php filter_var api and check
     * whether the input is valid.
     */
    private function runFilter($regexp, $input, $isValid): void
    {
        $r = filter_var(
            $input,
            FILTER_VALIDATE_REGEXP,
            ['options'=> ['regexp'=> $regexp]]
        );

        if ($isValid) {
            $this->assertEquals($input, $r);
        } else {
            $this->assertFalse($r);
        }
    }

    /**
     * @dataProvider cacheVarProvider
     */
    public function testCacheVar($input, $isValid): void {
        $this->runFilter(ReportGenerator::CHART_CACHEREF_REGEX, $input, $isValid);
    }

    /**
     * @dataProvider reportIdProvider
     */
    public function testReportIdVar($input, $isValid): void {
        $this->runFilter(ReportGenerator::REPORT_ID_REGEX, $input, $isValid);
    }

    /**
     * @dataProvider chartRefProvider
     */
    public function testChartRefVar($input, $isValid): void {
        $this->runFilter(ReportGenerator::REPORT_CHART_REF_REGEX, $input, $isValid);
    }

    /**
     * @dataProvider reportTmpProvider
     */
    public function testReportTmpVar($input, $isValid): void {
        $this->runFilter(ReportGenerator::REPORT_TMPDIR_REGEX, $input, $isValid);
    }
}
