parameters:
    sso:
        auth_referrer: 'https://xdmod:7000'
        show_local_login: true
        direct_link: false
        parameters:
            username:
                attribute:
                    - itname
                    - system_username
            first_name:
                attribute: firstName
                default: UNKNOWN
            middle_name:
                attribute: middleName
            last_name:
                attribute: lastName
            organization:
                attribute: orgId
            email_address:
                attribute: email
            system_username:
                attribute: system_username
                default: $username
    log_dir: '%env(XDMOD_LOG_DIR)%'
    google_recaptcha_site_key: '%env(GOOGLE_RECAPTCHA_SITE_KEY)%'
    center_related_acls:
        - cd
        - cs
services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $sectionName: database
    db.default:
        class: CCR\DB\iDatabase
        autowire: false
        factory:
            - CCR\DB
            - factory
    symfony_code:
        namespace: CCR\
        resource: ../src/
        exclude:
            - ../src/Entity/
            - ../src/Kernel.php
    legacy_code:
        namespace: CCR\
        resource: ../classes/CCR/
    CCR\DB\iDatabase:
        factory:
            - CCR\DB
            - factory
    CCR\Security\Authenticators\FormLoginAuthenticator:
        arguments:
            $options:
                username_parameter: username
                password_parameter: password
    CCR\Errors\ErrorController:
        tags:
            - controller.service_arguments
        arguments:
            - '@http_kernel'
            - error_controller
            - '@error_renderer'
    Symfony\Component\Dotenv\Command\DotenvDumpCommand: null
